version: '3.8'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=9271
      - POSTGRES_DB=appointmentdb
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgres
      - ./db:/docker-entrypoint-initdb.d/
    
  server:
    depends_on:
      - db
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    restart: unless-stopped
    env_file: ./server/.env
    ports:
      - 4000:4000
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=9271
      - DB_NAME=appointmentdb
      - DB_PORT=5432
    stdin_open: true
    tty: true

  client:
    depends_on:
      - server
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    restart: unless-stopped
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

volumes: 
  db-data:

