name: Trivy to Secret
on:
  workflow_dispatch:
jobs:
  code_analysis:
    runs-on: ubuntu-latest

    steps:
      # Define repo for output of results.
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # Installing Trivy for SBOM generation.
      - name: Install Trivy for SBOM Generation
        run: |
          curl -sSL https://github.com/aquasecurity/trivy/releases/download/v0.58.0/trivy_0.58.0_Linux-64bit.tar.gz | sudo tar xz -C /usr/local/bin
      
      # Generating SBOM using Trivy.
      - name: Generate Sarif using Trivy
        run: |
          trivy fs --format sarif --debug --scanners vuln --output output.sarif .
          
      # Official Github Action for uploading results in sarif format to Github Security tab.
      - name: Upload EPSS Data as SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          token: ${{ secrets.PAT }}
          sarif_file: output.sarif # sarif_file: ${{ steps.fetch-project.outputs.epss }}
          category: trivy
      
