name: Check Unused Dependencies (List)
on:
  workflow_dispatch:

env:
  NODE_VERSION: 16.x
  PACKAGE_DIRS: ". ./client ./server"

jobs:
  depcheck_with_alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: |
          for dir in ${{ env.PACKAGE_DIRS }}; do
            echo "Installing dependencies in $dir"
            cd "$dir" || exit
            npm install
            cd - || exit
          done
        shell: bash

      - name: Run Depcheck and Output Alerts
        run: |
          for dir in ${{ env.PACKAGE_DIRS }}; do
            echo "Running depcheck in $dir"
            cd "$dir" || exit
            output=$(npx depcheck || true)
            echo "$output"

        shell: bash

     # - name: Check Unused Dependencies
     #   run: |
     #     echo "Unused Dependencies:" > unused_dependencies.txt
     #     for dir in $PACKAGE_DIRS; do
     #       echo "Running depcheck in $dir..."
     #       cd "$dir" || exit
     #       depcheck | grep "Unused dependencies" | sed 's/Unused dependencies//' >> ../unused_dependencies.txt
     #       depcheck | grep "Unused devDependencies" | sed 's/Unused devDependencies//' >> ../unused_dependencies.txt
     #       cd - || exit
     #     done
     #     cat unused_dependencies.txt

     # - name: Upload Unused Dependencies
     #   uses: actions/upload-artifact@v3
     #   with:
     #     name: unused-dependencies-list
     #     path: unused_dependencies.txt
          
