name: CI Pipeline

on:
  workflow_dispatch:

env:
  NODE_VERSION: 16.x
  PACKAGE_DIRS: |
    .
    ./server
    ./client

jobs:
  depcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies and Cache
        run: |
          for dir in ${{ env.PACKAGE_DIRS }}; do
            cd "$dir" || exit
            npm install
            cd - || exit
          done

      - name: Run Depcheck
        run: |
          for dir in ${{ env.PACKAGE_DIRS }}; do
            cd "$dir" || exit
            npx depcheck > "$dir-unused-deps.txt"
            cd - || exit
          done
