name: Check Unused Dependencies (List)
on:
  workflow_dispatch:

jobs:
  check-unused-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Node.js Version
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Depcheck Globally
        run: npm install -g depcheck

      - name: Check Unused Dependencies
        env:
          PACKAGE_DIRS: ". ./server ./client"
        run: |
          echo "Unused Dependencies:" > unused_dependencies.txt
          for dir in $PACKAGE_DIRS; do
            echo "Running depcheck in $dir..."
            cd "$dir" || exit
            depcheck | grep "Unused dependencies" | sed 's/Unused dependencies//' >> ../unused_dependencies.txt
            depcheck | grep "Unused devDependencies" | sed 's/Unused devDependencies//' >> ../unused_dependencies.txt
            cd - || exit
          done
          cat unused_dependencies.txt

      - name: Upload Unused Dependencies
        uses: actions/upload-artifact@v3
        with:
          name: unused-dependencies-list
          path: unused_dependencies.txt
