name: Dependency Check
on:
  workflow_dispatch:

env:
  NODE_VERSION: 16.x # Node.js version

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
       
      - name: Find package.json Files
        id: locate-package-json
        run: |
          # Find all directories containing package.json
          find . -name "package.json" -exec dirname {} \; > package_dirs.txt

          # Export as a reusable list
          PACKAGE_DIRS=$(cat package_dirs.txt | tr '\n' ' ')
          echo "Found directories: $PACKAGE_DIRS"
          echo "PACKAGE_DIRS=$PACKAGE_DIRS" >> $GITHUB_ENV     
          
      # Installing dependencies from package.json files of repo.
      - name: Install Dependencies
        run: |
          for dir in ${{ env.PACKAGE_DIRS }}; do
            echo "Installing dependencies in $dir"
            cd "$dir" || exit
            npm install
            cd - || exit
          done
        shell: bash
          
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
            
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{ github.workspace }}/reports
