name: Check Unused Dependencies (List)
on:
  workflow_dispatch:

env:
  NODE_VERSION: 16.x
  PACKAGE_DIRS: ". ./client ./server"

jobs:
  generate_clean_sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: |
          for dir in ${{ env.PACKAGE_DIRS }}; do
            echo "Installing dependencies in $dir"
            cd "$dir" || exit
            npm install
            cd - || exit
          done
        shell: bash

      - name: Run Depcheck and Write to List
        run: |
          echo "Unused Dependencies:" > unused_dependencies.txt
            for dir in ${{ env.PACKAGE_DIRS }}; do
            echo "Running depcheck in $dir..."
            cd "$dir" || exit
            output=$(npx depcheck || true)
            if echo "$output" | grep -q "Unused dependencies"; then
              echo "$output" | sed -n '/Unused dependencies/,$p' | while IFS= read -r line; do
                if [[ $line == "*"* ]]; then
                  dep=$(echo "$line" | sed 's/* //')
                  echo "$dep" >> ../unused_dependencies.txt
                fi
              done
            fi

            # Parse and annotate unused devDependencies
            if echo "$output" | grep -q "Unused devDependencies"; then
              echo "$output" | sed -n '/Unused devDependencies/,$p' | while IFS= read -r line; do
                if [[ $line == "*"* ]]; then
                  dep=$(echo "$line" | sed 's/* //')
                  echo "$dep" >> ../unused_dependencies.tx
                fi
              done
            fi
            cd - || exit
          done
          cat unused_dependencies.txt
      
      - name: Install Syft for SBOM Generation
        run: |
          curl -sSL https://github.com/anchore/syft/releases/download/v1.17.0/syft_1.17.0_linux_amd64.tar.gz | tar xz -C /usr/local/bin syft

      - name: Generate SBOM using Syft
        run: |
          syft . --output cyclonedx-json=sbom.json

      - name: Extract Unused Dependencies from SBOM
        run: |
          echo "Extracting names of unused dependencies"
          unused_deps=$(cat unused_dependencies.txt)
    
          # Match unused dependencies against SBOM component names
          jq --argjson unused "$(echo "$unused_deps" | jq -R -s 'split("\n") | map(select(length > 0))')" '
            .components | map(select(.name as $name | $unused | index($name))) | map(.name)
          ' sbom.json > refined_unused.json

      - name: Remove Unused Dependencies from SBOM
        run: |
          echo "Removing unused dependencies from SBOM"
          unused_json=$(cat refined_unused.json)

          jq --argjson unused "$unused_json" '
          .components |= map(select(.name | index($unused[]) | not))
          ' sbom.json > filtered_sbom.json

      - name: Upload Unused Dependencies
        uses: actions/upload-artifact@v3
        with:
          name: filtered-sbom-json
          path: filtered_sbom.json
          
