name: Check Unused Dependencies

on:
  workflow_dispatch:

env:
  NODE_VERSION: 16.x
  PACKAGE_DIRS: ". ./server ./client"

jobs:
  depcheck_tool:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: |
          for dir in ${{ env.PACKAGE_DIRS }}; do
            echo "Installing dependencies in $dir"
            cd "$dir" || exit
            npm install
            cd - || exit
          done
          echo ${{ github.repository }}
        shell: bash

      - name: Run Depcheck for All Directories
        run: |
          for dir in ${{ env.PACKAGE_DIRS }}; do
            echo "Running depcheck in $dir"
            cd "$dir" || exit
            npx depcheck || true
            cd - || exit
          done
        shell: bash
