name: Get Data from Dep-Track
on:
  workflow_dispatch:

env:
  NODE_VERSION: 16.x
  PACKAGE_DIRS: ". ./client ./server"
  DEPENDENCY_TRACK_API_KEY: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
  DEPENDENCY_TRACK_BASE_URL: "https://32fd-62-90-190-70.ngrok-free.app"
  PROJECT_NAME: "Testing Dep-Track Workflow"  # Replace with repo name later

jobs:
  generate_clean_sbom:
    runs-on: ubuntu-latest

    steps:
    
      - name: Fetch Project ID
        id: fetch-project-id
        run: |
          project_id=$(curl -s -H "X-Api-Key: ${{ env.DEPENDENCY_TRACK_API_KEY }}" \
          "${{ env.DEPENDENCY_TRACK_BASE_URL }}/api/v1/projects" | jq -r '.[] | select(.name == "${{ env.PROJECT_NAME }}") | .id')
          echo "Project ID: $project_id"
          echo "project_id=$project_id" >> $GITHUB_ENV

      - name: Fetch EPSS Data
        id: fetch-epss
        run: |
          curl -s -H "X-Api-Key: ${{ env.DEPENDENCY_TRACK_API_KEY }}" \
          "${{ env.DEPENDENCY_TRACK_BASE_URL }}/projects/$project_id/epss" \
          -o epss.json
          echo "EPSS data fetched successfully."

      - name: Convert JSON to XML
        run: |
          cat epss.json | jq -r '
            {"epss_scores": .} | 
            toxml("epss_data")' > epss.xml
          echo "EPSS data converted to XML."

      - name: Output EPSS XML
        run: |
          cat epss.xml
