name: Semgrep Scan
on: [pull_request]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "./malicious-code-ruleset/"
          audit_on_failure: true  # Helps debugging failures
          error: true  # Fail PR if vulnerabilities are found
